name: Deploy slides to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - name: Install dependencies
        run: wget -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb && sudo apt install --yes /tmp/pandoc.deb
      - name: Run make
        run: make
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: site/
  deploy:
    needs: render
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
